name: "Chuck's Blog"
description: "GAMEDEV AND SHTUFF"

author: "Chuck"

url: ""#"http://charles-l.github.io"
baseurl: "http://charles-l.github.io"

markdown: redcarpet
permalink: :year/:month/:title.html
pygments: true
